env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-vars: 'error'
  react/jsx-uses-react: 'error'
  indent:
    - error
    - 2
  no-useless-catch:
    - 0
    - 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
